export const GET_API_DATA = "GET_API_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const CALCULATE_SUBTOTAL = "CALCULATE_SUBTOTAL";